#!/bin/sh

mkdir -p /var/mail/home
[ -e /var/mail/dovecot.user.conf ] || touch /var/mail/dovecot.user.conf
[ -e /var/mail/users ] || touch /var/mail/users
chown mail:mail /var/mail/home /var/mail/users
exec dovecot -F 2>&1

