#!/bin/sh

mkdir -p /var/mail/home
[ -e /var/mail/dovecot.user.conf ] || touch /var/mail/dovecot.user.conf
[ -e /var/mail/users ] || touch /var/mail/users


first_local_domain=$(grep LOCAL_DOMAINS /var/mail/exim.user.conf 2>/dev/null | cut -d= -f3 | cut -d: -f1 | tr -d " \t")
echo "postmaster@$first_local_domain" >/var/mail/postmaster_address

chown vmail:vmail /var/mail/home /var/mail/users
exec dovecot -F 2>&1

